enableGlobalCache: true

# Let's try first with pnp because its fast, we can always switch back to node-modules
#nodeLinker: pnp - sass not worked, but haven't tried dart sass
nodeLinker: node-modules
